/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MatchResults } from "@stencil/router";
export namespace Components {
    interface AppHome {
    }
    interface AppProfile {
        "match": MatchResults;
    }
    interface AppRoot {
    }
    interface DemoDataBinding {
    }
    interface DemoEvent {
        "alert": (params: any) => Promise<void>;
    }
    interface DemoIonicAlert {
    }
    interface DemoState {
    }
    interface DemoStencil {
        "name": string;
    }
    interface DemoUseIonic {
    }
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLDemoDataBindingElement extends Components.DemoDataBinding, HTMLStencilElement {
    }
    var HTMLDemoDataBindingElement: {
        prototype: HTMLDemoDataBindingElement;
        new (): HTMLDemoDataBindingElement;
    };
    interface HTMLDemoEventElement extends Components.DemoEvent, HTMLStencilElement {
    }
    var HTMLDemoEventElement: {
        prototype: HTMLDemoEventElement;
        new (): HTMLDemoEventElement;
    };
    interface HTMLDemoIonicAlertElement extends Components.DemoIonicAlert, HTMLStencilElement {
    }
    var HTMLDemoIonicAlertElement: {
        prototype: HTMLDemoIonicAlertElement;
        new (): HTMLDemoIonicAlertElement;
    };
    interface HTMLDemoStateElement extends Components.DemoState, HTMLStencilElement {
    }
    var HTMLDemoStateElement: {
        prototype: HTMLDemoStateElement;
        new (): HTMLDemoStateElement;
    };
    interface HTMLDemoStencilElement extends Components.DemoStencil, HTMLStencilElement {
    }
    var HTMLDemoStencilElement: {
        prototype: HTMLDemoStencilElement;
        new (): HTMLDemoStencilElement;
    };
    interface HTMLDemoUseIonicElement extends Components.DemoUseIonic, HTMLStencilElement {
    }
    var HTMLDemoUseIonicElement: {
        prototype: HTMLDemoUseIonicElement;
        new (): HTMLDemoUseIonicElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "app-profile": HTMLAppProfileElement;
        "app-root": HTMLAppRootElement;
        "demo-data-binding": HTMLDemoDataBindingElement;
        "demo-event": HTMLDemoEventElement;
        "demo-ionic-alert": HTMLDemoIonicAlertElement;
        "demo-state": HTMLDemoStateElement;
        "demo-stencil": HTMLDemoStencilElement;
        "demo-use-ionic": HTMLDemoUseIonicElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
    }
    interface AppProfile {
        "match"?: MatchResults;
    }
    interface AppRoot {
    }
    interface DemoDataBinding {
    }
    interface DemoEvent {
        "onLoaded"?: (event: CustomEvent<any>) => void;
    }
    interface DemoIonicAlert {
    }
    interface DemoState {
    }
    interface DemoStencil {
        "name"?: string;
    }
    interface DemoUseIonic {
    }
    interface IntrinsicElements {
        "app-home": AppHome;
        "app-profile": AppProfile;
        "app-root": AppRoot;
        "demo-data-binding": DemoDataBinding;
        "demo-event": DemoEvent;
        "demo-ionic-alert": DemoIonicAlert;
        "demo-state": DemoState;
        "demo-stencil": DemoStencil;
        "demo-use-ionic": DemoUseIonic;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "demo-data-binding": LocalJSX.DemoDataBinding & JSXBase.HTMLAttributes<HTMLDemoDataBindingElement>;
            "demo-event": LocalJSX.DemoEvent & JSXBase.HTMLAttributes<HTMLDemoEventElement>;
            "demo-ionic-alert": LocalJSX.DemoIonicAlert & JSXBase.HTMLAttributes<HTMLDemoIonicAlertElement>;
            "demo-state": LocalJSX.DemoState & JSXBase.HTMLAttributes<HTMLDemoStateElement>;
            "demo-stencil": LocalJSX.DemoStencil & JSXBase.HTMLAttributes<HTMLDemoStencilElement>;
            "demo-use-ionic": LocalJSX.DemoUseIonic & JSXBase.HTMLAttributes<HTMLDemoUseIonicElement>;
        }
    }
}
